---
title: "Ad Hoc Network Simulation"
output: word_document
---

Authors: 
"Jun Tan 26370084", "Peirang Xu 25117973","Roozbeh Faghihi Moghadam 25765752"

Part 1

```{r genNodes}
source("http://www.stat.berkeley.edu/users/nolan/data/nodeDensity.R")
genNodes = function(n) {
  x_new = c()
  y_new = c()
  while (length(x_new) < n & length(y_new) < n) {
    x = runif(n, min = 0, max = 100)
    y = runif(n, min = 0, max = 100)
    gridPts = expand.grid(x, y)
    zMax = ceiling(max(nodeDensity(gridPts$Var1, gridPts$Var2)))
    z = runif(n, min = 0, max = zMax)
    keep = nodeDensity(x, y) > z

    x_new = c(x_new, x[keep])

    y_new = c(y_new, y[keep])
  }
  return(matrix(c(x_new[1:n], y_new[1:n]), ncol = 2, byrow = FALSE))
}
```


Part 2

```{r findRc}
library(RSpectra)

findTranMat = function (mat, R){
  m = ifelse(apply(mat, 1, '>', R), 0, 1)
  ifelse(apply(mat,1,'<=', R), 1/colSums(m), 0)
}

getEigen2 = function (mat){
  m= eigen(mat)

  return(m$values[2])
}

findRange = function(mat){
  p = apply(mat, 1, function(x) max(x[x>0]))
  q = apply(mat, 1, function(x) min(x[x>0]))

  return(as.numeric(c(max(q), min(p))))
}

findRc = function (nodes, tol = 0.05){
  distBNodes = as.matrix(dist(nodes))
  Range = findRange (distBNodes)
  R_max = max(Range)
  R_min = min(Range)

  while(abs(R_max - R_min) > tol){
    R_mid = mean(c(R_min, R_max))
    transR = findTranMat(distBNodes, R_mid)
    eigenvalue2 = getEigen2(transR)

    if (all.equal(Mod(eigenvalue2), 1) > tol){
      R_max = R_mid
    } else R_min = R_mid
  }
  return(R_max)
}
```


Part 3

```{r simulation}
library(ggplot2)

#n = seq(from = 10, to = 30, by = 10)
n =c(10, 40, 70)
set.seed(12345)
NodeSimul = lapply(n, function(x) replicate(1000, genNodes(x)))
RcSimul = lapply(NodeSimul, function(x) apply(x, 3, findRc))

#Behavior of Rc
RcBehave <- data.frame("RcValues" = unlist(RcSimul), 
                       "Nodes" = rep(n, each = 1000))

#Density function for different node configuration
ggplot(data = RcBehave, aes(x = RcValues, 
                            colour = factor(Nodes))) +
  geom_density() 

#QQ Plot to explore distribution of Rc
plot(quantile(unlist(RcSimul), probs = seq(0.001, 0.999, by = 0.001)),
     xlab = "Theoratical Quantiles", ylab = "Sample Quantile")
```

a) As we see in density function, when number of nodes increase Rc decreases.

b) From density function and qqplot, we can iterpret that Rc distribution is right tailed.


c)
```{r plot network}
library(reshape)
library(ggplot2)

#Study network with 35 nodes

set.seed(12345)
NodeforPlot = replicate(1000, lapply(55,genNodes))
RcforPlot = sapply(NodeforPlot, findRc)

# Subset coordinates of 4 different Rc's
MinRcNode <- data.frame(NodeforPlot[[which(RcforPlot == min(RcforPlot))]])
MaxRcNode <-data.frame(NodeforPlot[[which(RcforPlot == max(RcforPlot))]])
MeanRcNode <- data.frame(NodeforPlot[[which.min(abs(RcforPlot - mean(RcforPlot)))]])
MedRcNode <-data.frame(NodeforPlot[[which.min(abs(RcforPlot - median(RcforPlot)))]])

```


```{r plotting min}
#Dataframe including distance and position of coordinates for MinRc
DistMinRc <- data.frame(melt(as.matrix(dist(MinRcNode), varnames = c("start", "end"))))
DistMinRc<- DistMinRc[DistMinRc$value <= (min(RcforPlot)+0.05),]

#Vectors for segment
Xmin <- MinRcNode[DistMinRc$X1 ,1]
XminEnd <- MinRcNode[DistMinRc$X2 ,1]
Ymin <- MinRcNode[DistMinRc$X1 ,2]
YminEnd <- MinRcNode[DistMinRc$X2 ,2]

#Graph Min
ggplot() + geom_point(data = MinRcNode, aes(x = MinRcNode[,1], y = MinRcNode[,2])) + 
  geom_segment(aes(x = Xmin, y = Ymin, xend = XminEnd, yend = YminEnd)) +
  xlab("X Coordinate") + ylab("Y Coordinate") + ggtitle("Plot Min")
```

```{r plotting max}
#Dataframe including distance and position of coordinates for MaxRc
DistMaxRc <- data.frame(melt(as.matrix(dist(MaxRcNode), varnames = c("start", "end"))))
DistMaxRc<- DistMaxRc[!(DistMaxRc$value > findRc(MaxRcNode)),]

#Vectors for segment
Xmax <- MaxRcNode[ ,1][DistMaxRc$X1]
XmaxEnd <- MaxRcNode[ ,1][DistMaxRc$X2]
Ymax <- MaxRcNode[ ,2][DistMaxRc$X1]
YmaxEnd <- MaxRcNode[ ,2][DistMaxRc$X2]

#Graph Max
ggplot() + geom_point(data = MaxRcNode, aes( x= MaxRcNode[,1], y = MaxRcNode[,2])) + 
  geom_segment(aes(x = Xmax, y = Ymax, xend = XmaxEnd, yend = YmaxEnd))+
  xlab("X Coordinate") + ylab("Y Coordinate") + ggtitle("Plot Max")
```


```{r plotting mean}

#Dataframe including distance and position of coordinates for MeanRc
DistMeanRc <- data.frame(melt(as.matrix(dist(MeanRcNode), varnames = c("start", "end"))))
DistMeanRc<- DistMeanRc[DistMeanRc$value <= findRc(MeanRcNode),]

#Vectors for segment
Xmean <- MeanRcNode[ ,1][DistMeanRc$X1]
XmeanEnd <- MeanRcNode[ ,1][DistMeanRc$X2]
Ymean <- MeanRcNode[ ,2][DistMeanRc$X1]
YmeanEnd <- MeanRcNode[ ,2][DistMeanRc$X2]

#Graph Mean
ggplot() + geom_point(data = MeanRcNode, aes(x = MeanRcNode[,1], y = MeanRcNode[,2])) + 
  geom_segment(aes(x = Xmean, y = Ymean, xend = XmeanEnd, yend = YmeanEnd))+
  xlab("X Coordinate") + ylab("Y Coordinate") + ggtitle("Plot Mean")
```

```{r plotting median}

#Dataframe including distance and position of coordinates for MedianRc
DistMedRc <- data.frame(melt(as.matrix(dist(MedRcNode), varnames = c("start", "end"))))
DistMedRc<- DistMedRc[DistMedRc$value <= (findRc(MedRcNode) + 0.05),]

#Vectors for segment
Xmed <- MedRcNode[ ,1][DistMedRc$X1]
XmedEnd <- MedRcNode[ ,1][DistMedRc$X2]
Ymed <- MedRcNode[ ,2][DistMedRc$X1]
YmedEnd <- MedRcNode[ ,2][DistMedRc$X2]

#Graph Median
ggplot() + geom_point(data = MedRcNode, aes(x = MedRcNode[,1], y = MedRcNode[,2])) + 
  geom_segment(aes(x = Xmed, y = Ymed, xend = XmedEnd, yend = YmedEnd))+
  xlab("X Coordinate") + ylab("Y Coordinate") + ggtitle("Plot Median")

```
